import type { CrmDashboardData } from "@/lib/crm/types";

const sheetsBase = "https://docs.google.com/spreadsheets/d/demo-sheet";
const calendarBase = "https://calendar.google.com/calendar/u/0/r/eventedit";
const driveBase = "https://drive.google.com/drive/folders/demo-drive";

export const mockCrmDashboardData: CrmDashboardData = {
  fetchedAt: "2026-04-29T08:30:00+02:00",
  clients: [
    {
      id: "sheet-row-1",
      fullName: "Jan Testowy",
      city: "Marki",
      phone: "600 100 200",
      email: "jan.testowy@example.pl",
      address: "Zielona 28",
      product: "PV + Magazyn energii",
      status: "Spotkanie umówione",
      notes: "Dom 160 m2, dach południe, chce szybką wycenę.",
      lastContactAt: "2026-04-28",
      nextAction: "Spotkanie",
      nextActionAt: "2026-04-30T14:00:00+02:00",
      sheetsUrl: `${sheetsBase}/edit#gid=0&range=A2`,
      calendarUrl: `${calendarBase}/event-1`,
      driveUrl: `${driveBase}/jan-testowy`,
    },
    {
      id: "sheet-row-2",
      fullName: "Anna Lis",
      city: "Piaseczno",
      phone: "602 345 678",
      email: "anna.lis@example.pl",
      address: "Kościuszki 15",
      product: "Pompa ciepła",
      status: "Oferta wysłana",
      notes: "Oferta wysłana 8 dni temu, decyzja po rozmowie z mężem.",
      lastContactAt: "2026-04-21",
      nextAction: "Telefon",
      nextActionAt: "2026-04-29T16:00:00+02:00",
      sheetsUrl: `${sheetsBase}/edit#gid=0&range=A3`,
      calendarUrl: `${calendarBase}/event-2`,
      driveUrl: `${driveBase}/anna-lis`,
    },
    {
      id: "sheet-row-3",
      fullName: "Krzysztof Bury",
      city: "Legionowo",
      phone: "609 222 333",
      email: null,
      address: "Słoneczna 4",
      product: "PV",
      status: "Spotkanie odbyte",
      notes: "Nie ma decyzji. Trzeba wrócić z finansowaniem.",
      lastContactAt: "2026-04-25",
      nextAction: "Follow-up dokumentowy",
      nextActionAt: "2026-04-28T10:00:00+02:00",
      sheetsUrl: `${sheetsBase}/edit#gid=0&range=A4`,
      calendarUrl: `${calendarBase}/event-3`,
      driveUrl: `${driveBase}/krzysztof-bury`,
    },
    {
      id: "sheet-row-4",
      fullName: "Marek Nowak",
      city: "Radom",
      phone: "601 400 500",
      email: "marek.nowak@example.pl",
      address: "Mickiewicza 9",
      product: "Magazyn energii",
      status: "Nowy lead",
      notes: "Lead z polecenia. Ma instalację PV 8 kW.",
      lastContactAt: "2026-04-29",
      nextAction: null,
      nextActionAt: null,
      sheetsUrl: `${sheetsBase}/edit#gid=0&range=A5`,
      calendarUrl: null,
      driveUrl: `${driveBase}/marek-nowak`,
    },
    {
      id: "sheet-row-5",
      fullName: "Tomasz Wójcik",
      city: "Wyszków",
      phone: "607 888 999",
      email: "tomasz.wojcik@example.pl",
      address: "Leśna 12",
      product: "PV",
      status: "Podpisane",
      notes: "Umowa podpisana, czeka na montaż.",
      lastContactAt: "2026-04-24",
      nextAction: "Follow-up dokumentowy",
      nextActionAt: "2026-05-06T09:00:00+02:00",
      sheetsUrl: `${sheetsBase}/edit#gid=0&range=A6`,
      calendarUrl: `${calendarBase}/event-4`,
      driveUrl: `${driveBase}/tomasz-wojcik`,
    },
  ],
  events: [
    {
      id: "event-1",
      clientId: "sheet-row-1",
      title: "Spotkanie: Jan Testowy",
      clientName: "Jan Testowy",
      city: "Marki",
      startsAt: "2026-04-30T14:00:00+02:00",
      endsAt: "2026-04-30T15:00:00+02:00",
      type: "in_person",
      location: "Zielona 28, Marki",
      calendarUrl: `${calendarBase}/event-1`,
    },
    {
      id: "event-2",
      clientId: "sheet-row-2",
      title: "Telefon: Anna Lis",
      clientName: "Anna Lis",
      city: "Piaseczno",
      startsAt: "2026-04-29T16:00:00+02:00",
      endsAt: "2026-04-29T16:15:00+02:00",
      type: "phone_call",
      location: "602 345 678",
      calendarUrl: `${calendarBase}/event-2`,
    },
    {
      id: "event-3",
      clientId: "sheet-row-3",
      title: "Follow-up dokumentowy: Krzysztof Bury",
      clientName: "Krzysztof Bury",
      city: "Legionowo",
      startsAt: "2026-04-28T10:00:00+02:00",
      endsAt: "2026-04-28T10:15:00+02:00",
      type: "doc_followup",
      location: null,
      calendarUrl: `${calendarBase}/event-3`,
    },
    {
      id: "event-4",
      clientId: "sheet-row-5",
      title: "Wysłać ofertę: Tomasz Wójcik",
      clientName: "Tomasz Wójcik",
      city: "Wyszków",
      startsAt: "2026-05-06T09:00:00+02:00",
      endsAt: "2026-05-06T09:15:00+02:00",
      type: "offer_email",
      location: null,
      calendarUrl: `${calendarBase}/event-4`,
    },
  ],
};
